
SELECT last_name, department_id 
FROM EMPLOYEES;

select * from DEPARTMENTS;
select * from EMPLOYEES;

SELECT 
	LAST_NAME, -- É DA TABELA EMPLOYEES
	DEPARTMENT_NAME -- É DA TABELA DEPARTMENTS
FROM 
	EMPLOYEES INNER JOIN DEPARTMENTS
	ON 
	EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;
	

SELECT 
	LAST_NAME, -- É DA TABELA EMPLOYEES
	DEPARTMENT_NAME -- É DA TABELA DEPARTMENTS
FROM 
	EMPLOYEES AS E INNER JOIN DEPARTMENTS AS D
	ON 
	E.DEPARTMENT_ID = D.DEPARTMENT_ID;

SELECT 
	EMP.LAST_NAME, -- É DA TABELA EMPLOYEES
	DEP.DEPARTMENT_NAME -- É DA TABELA DEPARTMENTS
FROM 
	EMPLOYEES AS EMP INNER JOIN DEPARTMENTS AS DEP
	ON 
	EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID;

SELECT 
	E.LAST_NAME, -- É DA TABELA EMPLOYEES
	D.DEPARTMENT_NAME, -- É DA TABELA DEPARTMENTS
	L.CITY -- É DA TABELA LOCATIONS
FROM 
	EMPLOYEES AS E -- o "AS" é opcional, pode fazer sem ele
	INNER JOIN 
	DEPARTMENTS AS D -- o "AS" é opcional, pode fazer sem ele
	ON 
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
	INNER JOIN 
	LOCATIONS AS L -- o "AS" é opcional, pode fazer sem ele
	ON L.LOCATION_ID = D.LOCATION_ID;

	
SELECT 
	E.LAST_NAME, -- É DA TABELA EMPLOYEES
	D.DEPARTMENT_NAME, -- É DA TABELA DEPARTMENTS
	L.CITY -- É DA TABELA LOCATIONS
FROM 
	EMPLOYEES E -- sem o "AS"
	INNER JOIN 
	DEPARTMENTS D -- sem o "AS"
	ON 
	E.DEPARTMENT_ID = D.DEPARTMENT_ID
	INNER JOIN 
	LOCATIONS L -- sem o "AS"
	ON L.LOCATION_ID = D.LOCATION_ID
WHERE E.MANAGER_ID = 149;



select apelido.last_name from EMPLOYEES apelido;

select colab.LAST_NAME, gestor.LAST_NAME
from
	EMPLOYEES colab
	INNER JOIN
	EMPLOYEES gestor
	ON
	colab.MANAGER_ID = gestor.EMPLOYEE_ID;



select colab.LAST_NAME AS "Colaborador", gestor.LAST_NAME as "Gestor"
from
	EMPLOYEES colab
	INNER JOIN
	EMPLOYEES gestor
	ON
	colab.MANAGER_ID = gestor.EMPLOYEE_ID;

select * from DEPARTMENTS where DEPARTMENT_ID = 180;

select * from EMPLOYEES where DEPARTMENT_ID = 180;

SELECT E.LAST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM
	EMPLOYEES E 
	INNER JOIN 
	DEPARTMENTS D
	ON
	(E.DEPARTMENT_ID = D.DEPARTMENT_ID);


	
SELECT E.LAST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM
	EMPLOYEES E 
	RIGHT OUTER JOIN 
	DEPARTMENTS D
	ON
	(E.DEPARTMENT_ID = D.DEPARTMENT_ID);



SELECT E.LAST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM
	EMPLOYEES E 
	LEFT OUTER JOIN 
	DEPARTMENTS D
	ON
	(E.DEPARTMENT_ID = D.DEPARTMENT_ID);



SELECT E.LAST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM
	EMPLOYEES E 
	LEFT OUTER JOIN 
	DEPARTMENTS D
	ON
	(E.DEPARTMENT_ID = D.DEPARTMENT_ID)
WHERE E.DEPARTMENT_ID IS NULL;


SELECT E.LAST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM
	EMPLOYEES E 
	FULL OUTER JOIN 
	DEPARTMENTS D
	ON
	(E.DEPARTMENT_ID = D.DEPARTMENT_ID);


-- Produto cartesiano (nunca fazer)
SELECT 
	E.LAST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM
	EMPLOYEES E, DEPARTMENTS D;

-- Usar INNER JOIN/LEFT OUTER JOIN/RIGHT OUTER JOIN para resolver problema do Produto Cartesiano	
SELECT E.LAST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM
	EMPLOYEES E 
	LEFT OUTER JOIN 
	DEPARTMENTS D
	ON
	(E.DEPARTMENT_ID = D.DEPARTMENT_ID);

